Update multiple portuguese translations
riseupnet/riseup_help pull request #708
Opened 2020-08-19 18:57 UTC by yyyyyyyan

I've updated the portuguese translation of 10 pages and added the translation for 1 page.

I was planning on updating the complete portuguese translation before sending the PR, but since I got a bit busy, I thought it'd be better if I split the updates into different PRs, so I wouldn't suddenly end up with a giant merge conflict or something like that.

I'm still working on the rest of the outdated and inexistent portuguese translations, though! Soon I'll send another PR with more translated pages ;)

2020-08-20 22:32 UTC, gusgustavo requested changes
Hello, I reviewed your PR. 
I made some suggestions and requests.
Thanks!

2020-08-20 22:32 UTC, gusgustavo commented on pages/about-us/canary/pt.md
> +Confirme se a saída diz "Good signature" e se o ID da chave é o mesmo que você verificou [[aqui, mais cedo. => network-security/certificates#complete-verification]] Se o texto estiver diferente, as i
Faltou adicionar um período final entre o link em markdown e a nova sentença "Se o texto".

2020-08-20 22:32 UTC, gusgustavo commented on pages/security/device-security/software-safety/pt.md
> +* Se você tem requisitos específicas para softwares ou softwares customizados para sua organização, atualizações automáticas podem causar interrupções em seu trabalho, já que algumas atualizações do
- [ ] Alterar gênero: "Se você tem requisitos específic**o**s"
- [ ] Remover letra extra: "atualizações do sistema operaciona**k**l"

2020-08-20 22:32 UTC, gusgustavo commented on pages/security/device-security/software-safety/pt.md
> +Quando possível, é melhor instalar software pela loja de aplicações oficial do seu sistema operacional, por várias razões:
Sugestão: Substituir "loja de aplicações" por "loja oficial de aplicativos".

2020-08-20 22:32 UTC, gusgustavo commented on pages/security/device-security/software-safety/pt.md
> +* **Autenticidade**: Aplicações na loja de aplicações oficial são assinadas pelo desenvolvedor e verificada pela loja de aplicações.
* **Autenticidade**: os apps na loja oficial de aplicativos são assinadas pelo desenvolvedor e verificada pela loja de aplicativos.

2020-08-20 22:32 UTC, gusgustavo commented on pages/security/device-security/software-safety/pt.md
> +* **Atualizações**: A loja de aplicações vai te ajudar a manter suas aplicações atualizadas.
Sugestão: A loja de aplicativos. E ao invés de aplicações "apps".

2020-08-20 22:32 UTC, gusgustavo commented on pages/security/device-security/software-safety/pt.md
> +* **Prevenção de Ataques de Side Loading**: Instalar uma aplicação por fora da loja oficial de aplicações é chamado de "side loading". Side loading é atualmente desabilitado por padrão no Android, im
- [ ] Sugestão mudar "aplicações" para "aplicativos".
- [ ] Remover palavra extra em inglês: "impossível no iOS, e é **is** habilitado por padrão"

2020-08-20 22:32 UTC, gusgustavo commented on pages/security/device-security/software-safety/pt.md
> +Nota: Você precisa de cuidado com a loja de aplicações oficial do Android, Google Play, já que é comum a existência de aplicações falsas que imitam e tentam impersonar determinada aplicação real.
- [ ] Sugestão: "Você precisa tomar cuidado com a loja oficial de aplicativo do Android..."
- [ ] Sugestão:"impersonar" por "tentam se passar por um determinado aplicativo verdadeiro."

2020-08-20 22:32 UTC, gusgustavo commented on pages/security/network-security/tor/pt.text
> +Segundo, por mais que o Tor em si seja seguro, outros programas instalados no seu computador podem não ser. Você precisa mudar alguns dos seus hábitos e reconfigurar o seu software! O Tor sozinho *NÃ
- [ ] Substituir esse link : https://torproject.org/docs/documentatin.html.en para https://support.torproject.org/pt-BR

2020-08-20 22:32 UTC, gusgustavo commented on pages/vpn/security-issues/pt.text
> +Uma conexão insegura ainda é insegura: Apesar da RiseupVPN anonimizar sua localização e te proteger da vigilância de seu Provedor de Acesso à Internet, assim que sua data é encaminhada com segurança
- [ ] Corrigir:"assim que os seus dados forem encaminhados com segurança para riseup.net, eles seguirão para a Internet como..."

2020-08-21 22:32 UTC, yyyyyyyan commented
Thank you very much, @gusgustavo! Just commited the update, fixing the errors and following your great suggestions :-)

2020-08-23 14:49 UTC, merged